### ISSUE TITLE
Exception in plugin GitHelper (231.1.4) PhpStorm 2023.1

### ISSUE THREAD

**Issue by ShadowByte-666** [itisokey/githelper#7]
Hello,

today, after updating PhpStorm I got this 2 Error from the GitHelper Plugin. (See Attachment)

Greetings 

[GitHelper-Error.txt](https://github.com/itisokey/githelper/files/11150207/GitHelper-Error.txt)

**Comment by lyulifeng** [comment]
Got it, Thank you for your feedback, I will fix these issues later. :)

**Comment by ShadowByte-666** [comment]
Hello,
I know you're probably busy. 
But it's such a pity, that the plugin is still not useable.

**Comment by lyulifeng** [comment]
Sry, I am really a little busy. This problem will be fixed in 231.1.5. I will ping you after the audit is passed. If you have any other suggestions about this plugin, feel free to put them forward :)

**Comment by lyulifeng** [comment]
Please try it with 231.1.5, it has been uploaded to the market.
